version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: kimdani/pos-backend:latest
    ports:
      - "8081:80"
    networks:
      - pos_system_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: kimdani/pos-backend:latest
    ports:
      - "8082:80"
    networks:
      - pos_system_network

  nginx:
    image: nginx:latest
    volumes:
      - /home/ec2-user/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - pos_system_network

networks:
  pos_system_network:
    driver: bridge
