version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: pos-backend
    restart: always
    networks:
      - pos_system_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: pos-frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
    networks:
      - pos_system_network

networks:
  pos_system_network:
    driver: bridge
