version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: pos-backend
    ports:
      - "8080:8081"
    restart: always
    networks:
      - pos_system_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: pos-front
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
    networks:
      - pos_system_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # Nginx가 외부 80번 포트로 요청을 받음
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - pos_system_network


networks:
  pos_system_network:
    name: pos_system_network
    driver: bridge
