name: Build and Deploy

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      SPRING_DATASOURCE_URL: ${{ secrets.DB_URL }}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.DB_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}


    steps:
      # 1. 레포지토리 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Secret 파일 준비
      - name: Prepare Secret File
        run: |
          mkdir -p backend/src/main/resources
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > backend/src/main/resources/application.properties

      - name: Print Database URL
        run: |
          echo "Database URL: $SPRING_DATASOURCE_URL"

      # 3. Spring Boot 백엔드 빌드
      - name: Build Backend
        run: |
          cd backend
          chmod +x mvnw
          ./mvnw clean package -DskipTests
          ls target/*.jar || (echo "JAR 파일 생성 실패!" && exit 1)

      # 4. React 프론트엔드 빌드
      - name: Build Frontend
        env:
          REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}
        run: |
          cd frontend
          echo "REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL" > .env
          npm ci --silent
          CI=false npm run build --silent

      # 5. Docker 이미지 빌드
      - name: Build Docker Images
        run: |
          docker build -t my-backend ./backend
          docker build -t my-frontend ./frontend

      # 6. Docker 이미지 배포 (예: Docker Hub)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Images
        run: |
          docker tag my-backend ${{ secrets.DOCKER_USERNAME }}/my-backend:latest
          docker tag my-frontend ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest
